### ISSUE TITLE
TypeError (reflect-metadata) on mysql-and other examples

### ISSUE THREAD

**Issue by JuBerndt** [jaystack/odata-v4-server#38]
npm test and npm start fails

i'm new with odata-v4-server and tried to run the mysql example on a installation of 

	- node v8.15.0
	- odata-v4-server v0.2.13
	- odata-v4-mysql v0.1.1
	- mysql v2.16.0
	- reflect-metadata v0.1.13

The metadata of the service could not be generated out of the model data.
I got the following error:

> node .

C:\jaydata\odata-v4-server-example-03\node_modules\reflect-metadata\Reflect.js:228
                throw new TypeError();
                ^

TypeError
    at Object.defineMetadata (C:\jaydata\odata-v4-server-example-03\node_modules\reflect-metadata\Reflect.js:228:23)
    at C:\jaydata\odata-v4-server-example-03\node_modules\odata-v4-server\build\lib\edm.js:946:25
    at DecorateProperty (C:\jaydata\odata-v4-server-example-03\node_modules\reflect-metadata\Reflect.js:553:33)
    at Object.decorate (C:\jaydata\odata-v4-server-example-03\node_modules\reflect-metadata\Reflect.js:123:24)
    at __decorate (C:\jaydata\odata-v4-server-example-03\lib\model.js:4:92)
    at Object.<anonymous> (C:\jaydata\odata-v4-server-example-03\lib\model.js:57:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

It seems there is a problem with the EntityType's.
I could not find any solution, how to define the navigation properties in the model file. 

Any ideas ?

Regards
Jürgen

**Comment by vipulw2011** [comment]
Hi @JuBerndt , any fix for this ?
